### ISSUE TITLE
HCO doesn't use a PHASE

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/hyperconverged-cluster-operator#102]
`oc get hco --all-namespaces` constantly displays nothing for a PHASE field.

Phases:
  - installing: creating component CRs
  - reconciling: install has already run.  Recreating missing CRs
  - running: HCO is happy
  - failed: HCO is reporting error

Example from virt-operator
https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-operator/kubevirt.go#L808

**Comment by djzager** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status is an interesting read

**Comment by djzager** [comment]
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/197
