### ISSUE TITLE
Deploy script fails due to broken link

### ISSUE THREAD

**Issue by isaacdorfman** [kubevirt/hyperconverged-cluster-operator#1046]
The script pointed to by "Using the HCO without OLM or Marketplace" in the readme tries to run kubectl apply -f on the link:
"https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/master/deploy/crds/scheduling-scale-performance01.crd.yaml" which is broken, together with some other broken links.

**Comment by erkanerol** [comment]
Fixed with #1048
