### ISSUE TITLE
HCO is managing the wrong CDI CRD

### ISSUE THREAD

**Issue by kincl** [kubevirt/hyperconverged-cluster-operator#1137]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The CDI v1beta1 CRD should include `.spec.config` but the CRD that the HCO manages does not have a number of those options in CDISpec.

**Anything else we need to know?**:

* https://github.com/kubevirt/hyperconverged-cluster-operator/commit/5695aaf7d69c44c8b9914810f308c92187a36bb5
* https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/apis/core/v1beta1/types.go#L317

This bug was filed per the discussion at https://kubernetes.slack.com/archives/C8ED7RKFE/p1613421610305400

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`):

v1.2.0

Tested with kubevirt-hyperconverged-operator.v2.5.2

- Kubernetes version (use `kubectl version`):

v1.19.0

**Comment by tiraboschi** [comment]
HCO consumes whatever CDI operator images produces with its csv-generator, I'd suspect that the issue is there.

**Comment by zcahana** [comment]
@kincl the CDI v1beta1 CRD had introduced the `.spec.config` field at CDI version v1.26.0 (see [here](https://github.com/kubevirt/containerized-data-importer/compare/v1.25.0...v1.26.0#diff-c57329496b7daf25f399f42ffcddcfd8ea09943f50d623653138a037e2ce1d34)), while the latest CDI version to make it into HCO 1.2 (and thereby OpenShift Virtualization v2.5.2) is v1.23.5 (see [here](https://github.com/kubevirt/hyperconverged-cluster-operator/commits/release-1.2) and search for "Bump CDI").

**Comment by kincl** [comment]
Okay great thanks @tiraboschi and @zcahana that all makes sense now
