### ISSUE TITLE
periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.7-hco-e2e-deploy-nightly-master-aws failed, hitting timeout

### ISSUE THREAD

**Issue by maya-r** [kubevirt/hyperconverged-cluster-operator#1157]
/kind bug
/triage build-watcher

FYI, this job is failing: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.7-hco-e2e-deploy-nightly-master-aws/1366237403093667840

**Comment by mhenriks** [comment]
Again:  https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.7-hco-e2e-deploy-nightly-master-aws/1366599724529881088
