### ISSUE TITLE
hco pods is running, but logs are spammed by cdi errors

### ISSUE THREAD

**Issue by pavolbrilla** [kubevirt/hyperconverged-cluster-operator#12]
hco depolyment went without hiccup, but after 10-15 of running cluster cdi lost most of pods, only cdi-operator is running, so I went to check hco pod, it is running but logs are spammed by:

{"level":"error","ts":1553704183.7050228,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"hyperconverged-controller","request":"kubevirt/hyperconverged-cluster","error":"cdis.cdi.kubevirt.io \"cdi-hyperconverged-cluster\" already exists","stacktrace":"github.com/kubevirt/hyperconverged-cluster-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/rhallisey/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubevirt/hyperconverged-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/rhallisey/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/kubevirt/hyperconverged-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/rhallisey/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/kubevirt/hyperconverged-cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/rhallisey/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/kubevirt/hyperconverged-cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/rhallisey/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/kubevirt/hyperconverged-cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/rhallisey/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Comment by lveyde** [comment]
Can you please test it with the following patches being applied:
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/11/commits   ?

**Comment by rthallisey** [comment]
Think this has been fixed given conversations on slack.
