### ISSUE TITLE
KubeVirt jsonpatch Annotations cannot be applied

### ISSUE THREAD

**Issue by rnetser** [kubevirt/hyperconverged-cluster-operator#1201]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Following [jsonpatch Annotations](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/docs/cluster-configuration.md#jsonpatch-annotations), tried to update KubeVirt.
Added the bellow annotation:
`    kubevirt.kubevirt.io/jsonpatch: |-
      [
        {
          "op": "add",
          "path": "/configuration/migrations",
          "value": "{'allowPostCopy': 'true'}"
        }
      ]`

Failed to apply the change on:

> error: hyperconvergeds.hco.kubevirt.io "kubevirt-hyperconverged" could not be patched: admission webhook "validate-hco.kubevirt.io" denied the request: invalid jsonPatch in the kubevirt.kubevirt.io/jsonpatch annotation: can only modify spec fields

**What you expected to happen**:
HCO should be updated successfully and change applied to KubeVirt CR.

**How to reproduce it (as minimally and precisely as possible)**:
100%
**Anything else we need to know?**:

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tiraboschi** [comment]
The feature is working as expected, I think we have only to amend its documentation providing better examples.

```
$ oc annotate -n kubevirt-hyperconverged hco kubevirt-hyperconverged kubevirt.kubevirt.io/jsonpatch='[{"op": "add", "path": "/spec/configuration/migrations", "value": {"allowPostCopy": true} }]'
hyperconverged.hco.kubevirt.io/kubevirt-hyperconverged annotated
$ oc get kubevirt -n kubevirt-hyperconverged kubevirt-kubevirt-hyperconverged -o json | jq .spec.configuration.migrations
{
  "allowPostCopy": true,
  "bandwidthPerMigration": "64Mi",
  "completionTimeoutPerGiB": 800,
  "parallelMigrationsPerCluster": 5,
  "parallelOutboundMigrationsPerNode": 2,
  "progressTimeout": 150
}
$ oc annotate --overwrite -n kubevirt-hyperconverged hco kubevirt-hyperconverged kubevirt.kubevirt.io/jsonpatch='[{"op": "add", "path": "/spec/configuration/migrations", "value": {"allowPostCopy": false} }]'
hyperconverged.hco.kubevirt.io/kubevirt-hyperconverged annotated
$ oc get kubevirt -n kubevirt-hyperconverged kubevirt-kubevirt-hyperconverged -o json | jq .spec.configuration.migrations
{
  "allowPostCopy": false,
  "bandwidthPerMigration": "64Mi",
  "completionTimeoutPerGiB": 800,
  "parallelMigrationsPerCluster": 5,
  "parallelOutboundMigrationsPerNode": 2,
  "progressTimeout": 150
}
```
