### ISSUE TITLE
Configuration in the HCO

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/hyperconverged-cluster-operator#13]
We want to have the HCO handle configuration for all component operators. Provide a mechanism/library/interface that each component operator can use to expose their configuration.

 - Create a standard for how component operators expose config
   - How should we default values?
   - What should be exposed to the user?
 - Create some code library/mechanism to expose config
   - Should configuration options be vendored from components?
   - Should options be centralized?

**Comment by phoracek** [comment]
I guess we will eventually need to make HCO more flexible, but to start with something radical: We should stay opinionated and strict about the "right" way to deploy the cluster. Ideally, none of underlying operators' attributes should be exposed. The only exception would be a scenario where there is no sane default or it is based on attribute of the cluster that is unknown to us (e.g. if there are no SR-IOV NICs available, we don't want to enable SR-IOV plugins).

Could we start making a list of (existing and planned) attributes for each operator? Maybe a Google document would be a better place to discuss that.

**Comment by booxter** [comment]
@phoracek even more radical, I don't see a problem to start SR-IOV device plugin with no devices, and to copy SR-IOV CNI plugin to a directory even if there is nothing to manage on a particular node.
