### ISSUE TITLE
Could not delete vmi on OKD Cluster

### ISSUE THREAD

**Issue by rupang790** [kubevirt/hyperconverged-cluster-operator#1443]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
To delete VMI, I tried to use cli ```kubectl delete -f vm.yaml```, but it is stuck as below:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/40801176/125753875-1a3259a2-3021-4442-83c6-73aa8ecc9236.png">

Actually before delete, when I tried to check the console on OKD WebUI, console was not shown.
Also ```service is not found``` message was occurred, when I tried to delete or stop vmi from OKD webUI.
![image](https://user-images.githubusercontent.com/40801176/125754086-329fcf52-b7a6-40da-91f5-f2cead005467.png)

Even though virt-launcher-xxx pod was deleted, vmi is not deleted as I wish.
How to solve this?

**What you expected to happen**:
Delete VMI 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create VMI
2. Delete VMI ('service not found' error occurred)
3. Delete virt-launcher-xxxx pod
4. Try to delete vmi with CLI and WebUI -> Not Delete

**Anything else we need to know?**:

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): 1.5.0
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration:
- Install tools: 
- Others: OKD 4.5 Cluster

**Comment by nunnatsa** [comment]
@davidvossel - could you please take a look?

**Comment by nunnatsa** [comment]
@rupang790 - I'm not sure I get the issue right. What do you mean by (2) and what is the difference from (4)?

Also, OKD 4.5 is too old for HCO 1.5.0. Please use 4.8

**Comment by rupang790** [comment]
@nunnatsa 
About the Version of OKD, I could not upgrade to 4.8 for now, because we try to fix some specific version of OKD currently.

Actually, after reboot the vm on vmi console by cli ```sudo systemctl reboot```, I could not handle lifecycle of vmi (such as start, restart or stop vmi) on WebUI at all. 
To sum up, I can no longer handle vmi via webui. So, I tried to remove the vmi through the oc command, but it failed. As the last, I removed the virt-launcher-xxx pod, but the vmi is still on the WebUI.

**Comment by tiraboschi** [comment]
Please consume HCO 1.3.0 on OKD 4.5.0

**Comment by rupang790** [comment]
> Please consume HCO 1.3.0 on OKD 4.5.0

**Comment by tiraboschi** [comment]
Can you please try deploying from release-1.3 branch?
I'll try reproducing as well.

**Comment by tiraboschi** [comment]
I successfully deployed and tested kubevirt-hyperconverged-operator.v1.3.0 from the stable channel of community-operators on OKD 4.5
