### ISSUE TITLE
Helm chart for deployment

### ISSUE THREAD

**Issue by nwmcsween** [kubevirt/hyperconverged-cluster-operator#1518]
/kind enhancement

Helm chart for non RH/OC deployments.

**Comment by erkanerol** [comment]
@nwmcsween thanks for bringing up this issue. Are you aware of this? https://github.com/kubevirt/hyperconverged-cluster-operator#using-the-hco-without-olm-or-marketplace

**Comment by nwmcsween** [comment]
Yes but curl installing a shell script is less than ideal for gitops style
deployments

**Comment by tiraboschi** [comment]
@nwmcsween 
under https://github.com/cwilkers/kubevirt-gitops you can find manifests to deploy OpenShift Virtualization with ArgoCD, you can easily adapt them for kubevirt/hyperconverged-cluster-operator
