### ISSUE TITLE
Generate the NMO objects

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/hyperconverged-cluster-operator#156]
The NMO manifest code is not vendored into the HCO.

Call out to the SSP code from manifest-templator:

    https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/tools/manifest-templator/manifest-templator.go

Replace templates:

    https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
    https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/templates/cluster_role.yaml.in
    https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/templates/operator.yaml.in

**Comment by fromanirh** [comment]
ack, will take care ASAP
