### ISSUE TITLE
ssp-operator Pod fails to start: No matches for kind infrastructure 

### ISSUE THREAD

**Issue by eshenayo** [kubevirt/hyperconverged-cluster-operator#1863]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
```console
curl https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/main/deploy/deploy.sh | bash
```
SSP Pod fails to start with crash loop

logs show:
```
{"level":"error","ts":1649154631.1769989,"logger":"setup","msg":"unable to create controller","controller":"SSP","error":"no matches for kind \"Infrastructure\" in version \"config.openshift.io/v1\"","stacktrace":"main.main\n\t/workspace/main.go:123\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:225"}
```
**What you expected to happen**:
Deploy SSP without errors

**How to reproduce it (as minimally and precisely as possible)**:
```console
git clone https://github.com/kubevirt/kubevirtci
cd kubevirtci/
export KUBEVIRT_PROVIDER=k8s-1.21 KUBEVIRT_NUM_NODES=2 KUBEVIRT_NUM_SECONDARY_NICS=1
make cluster-up
curl https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/main/deploy/deploy.sh | bash
```

**Anything else we need to know?**:
Perhaps this is related to [controller runtime issue 1191](https://github.com/kubernetes-sigs/controller-runtime/issues/1191)?
It may also be operator error. I am new to using this project.

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): I do not have oc installed, I am using kubectl
- Kubernetes version (use `kubectl version`): v1.21.0
- Cloud provider or hardware configuration: 
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           166
Model name:                      Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
Stepping:                        0
CPU MHz:                         1600.000
CPU max MHz:                     4700.0000
CPU min MHz:                     400.0000
BogoMIPS:                        3199.92
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
```
- Install tools:
- Others:

**Comment by tiraboschi** [comment]
Hi eshenayo,
AFAIK the SSP operator is not supposed to work outside k8s (and indeed `config.openshift.io/v1` is not available on plain k8s).
But I agree that our deploy script should correctly handle it skipping the SSP.

**Comment by eshenayo** [comment]
That makes sense. I wasn't entirely sure whether it would work but thought I'd try it out and see. Thanks for the swift response!
