### ISSUE TITLE
The trace collection seems to be broken

### ISSUE THREAD

**Issue by rmohr** [kubevirt/hyperconverged-cluster-operator#190]
We had a failing test run on a prow job. Aparentky containers did not become ready. In the logic which tries to collect information about the cluster, an error occured:

```
Found pods with errors cdi-apiservercdi-deploymentcdi-uploadproxyvirt-apivirt-controllerhyperconverged-cluster-operator
------------- cdi-apiservercdi-deploymentcdi-uploadproxyvirt-apivirt-controllerhyperconverged-cluster-operator
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'oc logs -h' for help and examples
make: *** [start] Error 1
```

**Comment by rmohr** [comment]
Job: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/rehearse-4269-canary-release-openshift-origin-installer-e2e-aws-4.2-cnv/13

**Comment by rthallisey** [comment]
bash..... looks like the vars gathered don't have spaces `cdi-apiservercdi-deploymentcdi-uploadproxyvirt-apivirt-controllerhyperconverged-cluster-operator` so looking for those pods fail.
