### ISSUE TITLE
Misspelled KubeVirt in Web UI

### ISSUE THREAD

**Issue by alexxa** [kubevirt/hyperconverged-cluster-operator#2]
It should be one word, not two. 

![screenshot from 2019-03-08 14-37-45](https://user-images.githubusercontent.com/6319198/54043564-36807480-41cd-11e9-9ac4-dc729cdeff02.jpg)

**Comment by rthallisey** [comment]
Using camel case causes the issue to appear in the UI.  This isn't something we should solve in this repo.
