### ISSUE TITLE
Create KubeVirt rate limiting static profiles

### ISSUE THREAD

**Issue by jcanocan** [kubevirt/hyperconverged-cluster-operator#2295]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
In https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2197 we have introduced a user-friendly mechanism to adjust the rate limiting `Query Per Second (QPS)` and `burst` values. Now, we want to create static profiles such as `highBurst` hiding the raw configuration values.

**What you expected to happen**:
It would be more easy for users to high scale their clusters allowing them to create a high number of VMs in a bulk if we have a `highBurst` profile which hides the raw numbers:

```yaml
apiVersion: hco.kubevirt.io/v1beta1
kind: hco
spec:
  tuningPolicy: highBurst
```
Values behind the `highBurst` profile are under discussion/testing in order to figure out possible downsides of increasing these values.

Issue tracked in: [CNV-14170](https://issues.redhat.com/browse/CNV-14170)
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): 4.14.0
- Kubernetes version (use `kubectl version`): any
- Cloud provider or hardware configuration: any
- Install tools:
- Others:

**Comment by tiraboschi** [comment]
@jcanocan is #2318 enough to consider this closed or are we targeting more profiles?

**Comment by jcanocan** [comment]
> @jcanocan is #2318 enough to consider this closed or are we targeting more profiles?
As far as I know, there's not plans for
We are exploring if a dynamic profile that follows the kubelet rate limits configuration would be useful. You can find further details in: https://issues.redhat.com/browse/CNV-27873. Nevertheless, we can close this issue for now since this would be a more dynamic approach

**Comment by jcanocan** [comment]
> @jcanocan is #2318 enough to consider this closed or are we targeting more profiles?

As far as I know, there's not plans for implementing more static profiles.

We are exploring if a dynamic profile that follows the kubelet rate limits configuration would be useful. You can find further details in: https://issues.redhat.com/browse/CNV-27873. Nevertheless, we can close this issue for now since this would be a more dynamic approach and I will open a new issue in the future.

Many thanks for the remainder.
