### ISSUE TITLE
v1.10.0 image pull errors

### ISSUE THREAD

**Issue by ianb-mp** [kubevirt/hyperconverged-cluster-operator#2712]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Attempting to install the Kubevirt HCO operator onto Openshift/OKD cluster via web console fails.

Looking at the pods in the `kubevirt-hyperconverged` namespace I see pods for hco-operator and hco-webhook are failing to deploy with `ErrImagePull` and `manifest unknown` errors e.g.
```
Warning  Failed          6s    kubelet            Failed to pull image "quay.io/kubevirt/hyperconverged-cluster-operator@sha256:9a5f03e3fa84aaa07cc334036083a66ffbd467a8e1a1a9acfdfaed733873e6fe": rpc error: c │
│ ode = Unknown desc = reading manifest sha256:9a5f03e3fa84aaa07cc334036083a66ffbd467a8e1a1a9acfdfaed733873e6fe in quay.io/kubevirt/hyperconverged-cluster-operator: manifest unknown                               │
│   Warning  Failed          6s    kubelet            Error: ErrImagePull           

Warning  Failed          24s (x4 over 112s)  kubelet            Failed to pull image "quay.io/kubevirt/hyperconverged-cluster-webhook@sha256:529980188e84fcc10a312f837e5876bc4cd4741847e794692b9a26e62f04f5b5": │
│  rpc error: code = Unknown desc = reading manifest sha256:529980188e84fcc10a312f837e5876bc4cd4741847e794692b9a26e62f04f5b5 in quay.io/kubevirt/hyperconverged-cluster-webhook: manifest unknown                   │
│   Warning  Failed          24s (x4 over 112s)  kubelet            Error: ErrImagePull               
```

**What you expected to happen**:
Operator install should complete successfully

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to install Kubevirt hco operator on Openshift/OKD 1.14 cluster via the OperatorHub (cluster web console)
 
**Anything else we need to know?**:

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): 1.10.0
- Kubernetes version (use `kubectl version`): v1.27.1-3443+19254894103e33-dirty
- Cloud provider or hardware configuration: bare metal x86_64
- Install tools:
- Others:

**Comment by nunnatsa** [comment]
Please use version 1.10.1

**Comment by ianb-mp** [comment]
ok, I will try. I'm waiting on this PR https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3829

**Comment by nunnatsa** [comment]
@ianb-mp - sorry for the delay. I think it should work now, in v1.10.7

Could you please verify and close the issue if it working?

**Comment by ianb-mp** [comment]
It looks good now, thanks
