### ISSUE TITLE
Getting cert errors

### ISSUE THREAD

**Issue by gtomilko** [kubevirt/hyperconverged-cluster-operator#2858]
OKD version: 4.14.0-0.okd-2024-01-06-084517
KubeVirt HyperConverged Cluster Operator version: 1.10.7

Installed operator from OKD operatorHub
When do Create HyperConverged getting error:
Fix the following errors:
    Error "failed calling webhook "mutate-hyperconverged-hco.kubevirt.io": failed to call webhook: Post "https://hco-webhook-service.kubevirt-hyperconverged.svc:4343/mutate-hco-kubevirt-io-v1beta1-hyperconverged?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority" for field "undefined".

Please advise

**Comment by tiraboschi** [comment]
I tried reproducing exactly with that two versions but it worked as expected for me.
@gtomilko is it still reproducible or was it just a transient issue?
