### ISSUE TITLE
Web Console and CLI installation not the same

### ISSUE THREAD

**Issue by manas-suleman** [kubevirt/hyperconverged-cluster-operator#2982]
**What happened**:
OKD4.15 [documentation](https://docs.okd.io/4.15/virt/install/installing-virt.html) describes two methods of installing KubeVirt Hyperconverged Cluster Operator, using webUI and CLI.
When installing from the webUI, you get the "kubevirt hyperconverged cluster operator" as expected. (I'm using channel 1.10.7 instead of stable because of #2954)
![image](https://github.com/kubevirt/hyperconverged-cluster-operator/assets/110912588/1093fbe9-ae8e-4d3d-a4d5-d905728ed65c)

When following the command-line steps, you only get "community kubevirt hyperconverged".
![image](https://github.com/kubevirt/hyperconverged-cluster-operator/assets/110912588/7c400285-c19a-444f-99dd-52201d6ac3de)

Could I be missing something obvious here?

**What you expected to happen**:
Same results from WebUI and CLI installation methods.

**How to reproduce it (as minimally and precisely as possible)**:
Install kubevirt hyperconverged cluster operator using the webUI, uninstall it and then install it again from the command-line.

**Additional context**:
NA

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): v1.28.2-3598+6e2789bbd58938-dirty
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): Fedora CoreOS 39.20240210.3.0
- Kernel (e.g. `uname -a`): 6.7.4-200.fc39.x86_64
- Install tools: N/A
- Others: N/A

**Comment by tiraboschi** [comment]
This is expected and it doesn't depend on the installation method. You are simply looking at different things:
` community-kubevirt-hyperconverged` is the package name, see: https://github.com/kubevirt/hyperconverged-cluster-operator/blob/84c79b00720e32c54f1a25baff18a1e03f095586/deploy/olm-catalog/community-kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml#L1
while `KubeVirt HyperConverged Cluster Operator` is the displayName, see: https://github.com/kubevirt/hyperconverged-cluster-operator/blob/84c79b00720e32c54f1a25baff18a1e03f095586/deploy/olm-catalog/community-kubevirt-hyperconverged/1.11.0/manifests/kubevirt-hyperconverged-operator.v1.11.0.clusterserviceversion.yaml#L188C3-L188C14
