### ISSUE TITLE
[Namespace stuck in terminating after Kubevirt operator cleanup] : Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: upload.cdi.kubevirt.io/v1alpha1: the server is currently unable to handle the request 

### ISSUE THREAD

**Issue by kcns008** [kubevirt/hyperconverged-cluster-operator#593]
status:
  phase: Terminating
  conditions:
    - type: NamespaceDeletionDiscoveryFailure
      status: 'True'
      lastTransitionTime: '2020-05-25T14:37:15Z'
      reason: DiscoveryFailed
      message: >-
        Discovery failed for some groups, 1 failing: unable to retrieve the
        complete list of server APIs: upload.cdi.kubevirt.io/v1alpha1: the
        server is currently unable to handle the request

After installing Kubevirt Operator and then cleanup:
All deleted Namespace going to Terminating State and stuck at 
" Discovery failed for some groups, 1 failing: unable to retrieve the
        complete list of server APIs: upload.cdi.kubevirt.io/v1alpha1: the
        server is currently unable to handle the request
"

**Version**
4.4.0-0.okd-2020-04-21-163702-beta4

**How reproducible**
- create OKD 4.4 cluster and install Kubevirt with:
$ curl https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/master/deploy/deploy.sh | bash

Then remove Kubevirt Operator by removing CRD and namespace

**Comment by silenceper** [comment]
same issue.
/reopen

**Comment by tiraboschi** [comment]
@silenceper can you please provide some detail on the version where you hit this?

Please notice that we have an e2e test explicitly covering this scenario and it's constantly passing,
see: https://github.com/kubevirt/hyperconverged-cluster-operator/blob/main/hack/test_delete_ns.sh

**Comment by silenceper** [comment]
when i delete apiservice like v1alpha1.upload.cdi.kubevirt.io, then ns delete success.

**Comment by tiraboschi** [comment]
yes, but it should not happen at all.
@silenceper which version of HCO did you deployed?

**Comment by tiraboschi** [comment]
closing due to lack of info,
please feel free to reopen if you have a valid reproducer
