### ISSUE TITLE
actually publish on operatorhub

### ISSUE THREAD

**Issue by ibotty** [kubevirt/hyperconverged-cluster-operator#606]
It seems that hco is, in fact, not published on operatorhub:
 https://operatorhub.io/?keyword=hyperconverged

If that's intentional, the readme should document that it's not yet on operatorhub.

**Comment by ibotty** [comment]
Found operator-framework/community-operators#1099 which lists the removal.

**Comment by gmarcy** [comment]
I think part of the issue is that when you look at places like
https://github.com/kubevirt/hyperconverged-cluster-operator/releases
you get the impression that nothing has been going on here.

Is there a reason for all the release branches but no git releases ?

**Comment by orenc1** [comment]
Hi,
HCO is currently not in `community-operators` (and therefore not in operatorhub.io) to avoid collision with another appregistry source.
However, you can create an operator source on your cluster to resolve the content of this repo using the yaml file in the kustomize folder:
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/deploy/kustomize/marketplace/operator_source.yaml

Then, KubeVirt HyperConverged Cluster Operator will be available in the OperatorHub in your cluster.

Note that in the upcoming months appregistry will be shifted to new OLM's index-image packaging format.

**Comment by ibotty** [comment]
Still an issue.
/remove-lifecycle stale

**Comment by orenc1** [comment]
HCO is now published on OperatorHub.io
https://operatorhub.io/operator/community-kubevirt-hyperconverged

It will be updated upon tagging a version in:
https://github.com/kubevirt/hyperconverged-cluster-operator/tags

**Comment by ibotty** [comment]
Yeah!   Thanks for making that happen.
