### ISSUE TITLE
deploy_kustomize.sh uses  non-portable paths

### ISSUE THREAD

**Issue by colonwq** [kubevirt/hyperconverged-cluster-operator#726]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
deploy_kustomize.sh has [two calls to sed](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/deploy/kustomize/deploy_kustomize.sh#L24-L25) which are relative to the base directory of the git repo.

These calls fail if the script is not ran from the base directory of the git repo.

**What you expected to happen**:
The sed calls should be able to run from any directory including the kustomize directory

**How to reproduce it (as minimally and precisely as possible)**:
cd deploy/kustomize
./deploy_kustomize.sh

**Anything else we need to know?**:

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by colonwq** [comment]
See PR #727

**Comment by orenc1** [comment]
Thanks @colonwq , your PR has been merged. Closing this issue.
