### ISSUE TITLE
HCO without OLM or Marketplace deploy.sh missing hostpath-provisioner crd

### ISSUE THREAD

**Issue by kmorning** [kubevirt/hyperconverged-cluster-operator#745]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
After using the deploy.sh script, the hostpath-provisioner-operator pod was in crash loop.

**What you expected to happen**:
All pods running after running deploy.sh

**How to reproduce it (as minimally and precisely as possible)**:
run the deploy script, check the pods

**Anything else we need to know?**:
I was able to resolve the problem by manually installing the hostpath-provisioner crd
`kubectl create -f https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/master/deploy/crds/hostpath-provisioner00.crd.yaml`
Looking at the deploy.sh, I can see that the crd for this is missing.  

Also the following crd in the deploy script fails, as the url doesn't exist.
`kubectl create -f https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/master/deploy/crds/node-maintenance00.crd.yaml`

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`):
N/A
- Kubernetes version (use `kubectl version`):
v1.18.6
- Cloud provider or hardware configuration:
Bare metal native kubernetes
- Install tools:
- Others:

**Comment by orenc1** [comment]
Hi @kmorning , thanks for submitting the issue.

- node maintenance operator is now no longer of the kubevirt-hyperconverged solution, so its CRD has been removed from the `deploy/crds` directory.
- host-path-provisioner CRD was indeed missing from the `deploy.sh` script.

Both addressed in #758 

/close
