### ISSUE TITLE
./hack/make_local.py fails with invalid syntax

### ISSUE THREAD

**Issue by ArthurSens** [kubevirt/hyperconverged-cluster-operator#873]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Tried to run HCO locally, following [docs/run-locally.md](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/docs/run-locally.md).
I've chosen to run with kubevirtci, with the following steps:
```
export KUBEVIRT_PROVIDER=k8s-1.17
make cluster-up
export KUBECONFIG=_kubevirtci/_ci-configs/k8s-1.17/.kubeconfig
make local
```

`make local` failed with following logs:
```
./hack/make_local.sh
+ LOCAL_DIR=_local
+ FORMAT=txt
+ set -o allexport
+ source hack/config
++ KUBEVIRT_VERSION=20200922_3653b1f1b
++ CDI_VERSION=v1.23.3
++ NETWORK_ADDONS_VERSION=v0.42.1
++ SSP_VERSION=v1.2.1
++ NMO_VERSION=v0.7.0
++ HPPO_VERSION=v0.5.2
++ HPP_VERSION=v0.5.1
++ CONVERSION_CONTAINER_VERSION=v2.0.0
++ VMWARE_CONTAINER_VERSION=v2.0.0-8
++ VM_IMPORT_VERSION=v0.2.2
++ CONTAINER_REGISTRY=quay.io/kubevirt
++ RELEASE_DELTA=0
++ PACKAGE_DIR=./deploy/olm-catalog/kubevirt-hyperconverged
+++ ls -d ./deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/ ./deploy/olm-catalog/kubevirt-hyperconverged/0.0.2/ ./deploy/olm-catalog/kubevirt-hyperconverged/0.0.3/ ./deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/ ./deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/ ./deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/ ./deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/
+++ awk NR==1
+++ cut -d / -f 5
+++ sort -rV
++ CSV_VERSION=1.3.0
+++ ls -d ./deploy/olm-catalog/kubevirt-hyperconverged/0.0.1/ ./deploy/olm-catalog/kubevirt-hyperconverged/0.0.2/ ./deploy/olm-catalog/kubevirt-hyperconverged/0.0.3/ ./deploy/olm-catalog/kubevirt-hyperconverged/1.0.0/ ./deploy/olm-catalog/kubevirt-hyperconverged/1.1.0/ ./deploy/olm-catalog/kubevirt-hyperconverged/1.2.0/ ./deploy/olm-catalog/kubevirt-hyperconverged/1.3.0/
+++ awk NR==2
+++ sort -rV
+++ cut -d / -f 5
++ REPLACES_CSV_VERSION=1.2.0
+ set +o allexport
+ mkdir -p _local
+ ./hack/make_local.py _local txt
  File "./hack/make_local.py", line 13
    return f'{env}={environ.get(env)}'
                                     ^
SyntaxError: invalid syntax
Makefile:133: recipe for target 'local' failed
make: *** [local] Error 1
```
Not sure if a specific python version is required, but I couldn't find anything on the documentation anyways.

**What you expected to happen**:
`make local` to not fail

**How to reproduce it (as minimally and precisely as possible)**:
Run the same commands as I did

**Anything else we need to know?**:
I'm trying to start a functional environment to run KubeVirt VMs and I think HCO is the way to go, but I was not sure where to ask for help with this one, please let me know if this is not the correct place.

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by nunnatsa** [comment]
@ArthurSens, thanks for the report. What is the python version?

**Comment by ArthurSens** [comment]
I failed with python 2.7.17

but well, I've changed make_local.sh to use python3 and it worked. Thanks
