### ISSUE TITLE
Job periodic-hco-push-nightly-build-master of type periodic ended with state failure.

### ISSUE THREAD

**Issue by dhiller** [kubevirt/hyperconverged-cluster-operator#935]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/triage build-watcher

**What happened**:

Job [periodic-hco-push-nightly-build-master](https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml#L2) failed: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-hco-push-nightly-build-master/1326344633935990784

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by phoracek** [comment]
Failed again https://storage.googleapis.com/kubevirt-prow/logs/periodic-hco-push-nightly-build-master/1326344633935990784/build-log.txt

**Comment by oshoval** [comment]
Failed again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-hco-push-nightly-build-master/1328518961691627520
