### ISSUE TITLE
README missing prerequisite on QUAY user

### ISSUE THREAD

**Issue by sandrobonazzola** [kubevirt/hyperconverged-cluster-operator#982]
/kind bug

**What happened**:
Reading README, found:

```
# Add the unreleases bundle source
$ curl https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/master/tools/quay-registry.sh | bash -s $QUAY_USERNAME $QUAY_PASSWORD
```
so the installation assume user has a QUAY login but it wasn't mentioned as prerequisite.

**What you expected to happen**:

Either not require a QUAY user or being mentioned that a prerequisite to complete the installation is having one.

**How to reproduce it (as minimally and precisely as possible)**:
Just read the documentation and apply it as it is written.

**Anything else we need to know?**: I don't think so

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): master README
- Kubernetes version (use `kubectl version`): v1.19.0
- Cloud provider or hardware configuration: bare metal deployment 3 master / 2 workers
- Install tools: OKD 4.6 installer

**Comment by orenc1** [comment]
This section is obsolete.
The `OperatorSource` object has been deprecated by OLM since OKD/OCP 4.6.
Need to rewrite this section to support the index-image workflow.
I'll work on it. Thanks for bringing that up.

**Comment by sandrobonazzola** [comment]
@orenc1 any update?

**Comment by orenc1** [comment]
Hi Sandro,
I updated the relevant README paragraph with today's method of consuming the unreleased bundles.
#1161 

Thanks
